const TEAM_LOGOS = {
    "SRH": "https://b.zmtcdn.com/data/edition_assets/177392584654815.png",
    "RR": "https://b.zmtcdn.com/data/edition_assets/177392584654411.png",
    "LSG": "https://b.zmtcdn.com/data/edition_assets/177392584655019.png",
    "PBKS": "https://b.zmtcdn.com/data/edition_assets/177392584654918.png",
    "DC": "https://b.zmtcdn.com/data/edition_assets/177392584654612.png",
    "CSK": "https://b.zmtcdn.com/data/edition_assets/177392584654613.png",
    "KKR": "https://b.zmtcdn.com/data/edition_assets/177392584655020.png",
    "RCB": "https://b.zmtcdn.com/data/edition_assets/177392584654917.png",
    "GT": "https://b.zmtcdn.com/data/edition_assets/177392584654816.png",
    "MI": "https://b.zmtcdn.com/data/edition_assets/177392584654714.png",
    "TBD": "https://media.insider.in/image/upload/c_crop,g_custom/v1774013615/xdfz9gcgg5ffikddsoir.png"
};

const TEAMS_INFO = {
    "CSK": { name: "Chennai Super Kings", cssClass: "csk" },
    "DC": { name: "Delhi Capitals", cssClass: "dc" },
    "PBKS": { name: "Punjab Kings", cssClass: "pbks" },
    "SRH": { name: "Sunrisers Hyderabad", cssClass: "srh" },
    "RR": { name: "Rajasthan Royals", cssClass: "rr" },
    "GT": { name: "Gujarat Titans", cssClass: "gt" },
    "KKR": { name: "Kolkata Knight Riders", cssClass: "kkr" },
    "MI": { name: "Mumbai Indians", cssClass: "mi" },
    "RCB": { name: "Royal Challengers Bengaluru", cssClass: "rcb" },
    "LSG": { name: "Lucknow Super Giants", cssClass: "lsg" }
};

const matchesData = [
    {
        id: "m1",
        matchNumber: "Match 46",
        team1: { name: "Gujarat Titans", short: "GT", cssClass: "gt", logo: TEAM_LOGOS["GT"] },
        team2: { name: "Punjab Kings", short: "PBKS", cssClass: "pbks", logo: TEAM_LOGOS["PBKS"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "03", month: "May", full: "Sun, 3 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-03T19:30:00+05:30",
        venue: "Narendra Modi Stadium, Ahmedabad",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m2",
        matchNumber: "Match 47",
        team1: { name: "Mumbai Indians", short: "MI", cssClass: "mi", logo: TEAM_LOGOS["MI"] },
        team2: { name: "Lucknow Super Giants", short: "LSG", cssClass: "lsg", logo: TEAM_LOGOS["LSG"] },
        heroBg: "",
        date: { dayStr: "Mon", dayNum: "04", month: "May", full: "Mon, 4 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-04T19:30:00+05:30",
        venue: "Wankhede Stadium, Mumbai",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m3",
        matchNumber: "Match 48",
        team1: { name: "Delhi Capitals", short: "DC", cssClass: "dc", logo: TEAM_LOGOS["DC"] },
        team2: { name: "Chennai Super Kings", short: "CSK", cssClass: "csk", logo: TEAM_LOGOS["CSK"] },
        heroBg: "https://media.insider.in/image/upload/c_crop,g_custom/v1776493925/aw9gif15vsn32uq0tbbd.jpg",
        date: { dayStr: "Tue", dayNum: "05", month: "May", full: "Tue, 5 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-05T19:30:00+05:30",
        venue: "Arun Jaitley Stadium, Delhi",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m4",
        matchNumber: "Match 49",
        team1: { name: "Sunrisers Hyderabad", short: "SRH", cssClass: "srh", logo: TEAM_LOGOS["SRH"] },
        team2: { name: "Punjab Kings", short: "PBKS", cssClass: "pbks", logo: TEAM_LOGOS["PBKS"] },
        heroBg: "https://media.insider.in/image/upload/c_crop,g_custom/v1777278688/asi1tmzm0rghhba2ntzh.jpg",
        date: { dayStr: "Wed", dayNum: "06", month: "May", full: "Wed, 6 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-06T19:30:00+05:30",
        venue: "Rajiv Gandhi International Stadium, Hyderabad",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m5",
        matchNumber: "Match 50",
        team1: { name: "Lucknow Super Giants", short: "LSG", cssClass: "lsg", logo: TEAM_LOGOS["LSG"] },
        team2: { name: "Royal Challengers Bengaluru", short: "RCB", cssClass: "rcb", logo: TEAM_LOGOS["RCB"] },
        heroBg: "",
        date: { dayStr: "Thu", dayNum: "07", month: "May", full: "Thu, 7 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-07T19:30:00+05:30",
        venue: "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m6",
        matchNumber: "Match 51",
        team1: { name: "Delhi Capitals", short: "DC", cssClass: "dc", logo: TEAM_LOGOS["DC"] },
        team2: { name: "Kolkata Knight Riders", short: "KKR", cssClass: "kkr", logo: TEAM_LOGOS["KKR"] },
        heroBg: "",
        date: { dayStr: "Fri", dayNum: "08", month: "May", full: "Fri, 8 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-08T19:30:00+05:30",
        venue: "Arun Jaitley Stadium, Delhi",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m7",
        matchNumber: "Match 52",
        team1: { name: "Rajasthan Royals", short: "RR", cssClass: "rr", logo: TEAM_LOGOS["RR"] },
        team2: { name: "Gujarat Titans", short: "GT", cssClass: "gt", logo: TEAM_LOGOS["GT"] },
        heroBg: "https://media.insider.in/image/upload/c_crop,g_custom/v1776318164/a0cjrh1nghxun1ilq5rn.jpg",
        date: { dayStr: "Sat", dayNum: "09", month: "May", full: "Sat, 9 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-09T19:30:00+05:30",
        venue: "Sawai Mansingh Stadium, Jaipur",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m8",
        matchNumber: "Match 53",
        team1: { name: "Chennai Super Kings", short: "CSK", cssClass: "csk", logo: TEAM_LOGOS["CSK"] },
        team2: { name: "Lucknow Super Giants", short: "LSG", cssClass: "lsg", logo: TEAM_LOGOS["LSG"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "10", month: "May", full: "Sun, 10 May 2026" },
        time: "3:30 PM",
        datetime: "2026-05-10T15:30:00+05:30",
        venue: "MA Chidambaram Stadium, Chennai",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m9",
        matchNumber: "Match 54",
        team1: { name: "Royal Challengers Bengaluru", short: "RCB", cssClass: "rcb", logo: TEAM_LOGOS["RCB"] },
        team2: { name: "Mumbai Indians", short: "MI", cssClass: "mi", logo: TEAM_LOGOS["MI"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "10", month: "May", full: "Sun, 10 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-10T19:30:00+05:30",
        venue: "Shaheed Veer Narayan Singh International Cricket Stadium, Raipur",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m10",
        matchNumber: "Match 55",
        team1: { name: "Punjab Kings", short: "PBKS", cssClass: "pbks", logo: TEAM_LOGOS["PBKS"] },
        team2: { name: "Delhi Capitals", short: "DC", cssClass: "dc", logo: TEAM_LOGOS["DC"] },
        heroBg: "https://media.insider.in/image/upload/c_crop,g_custom,q_auto/v1776930304/xqhf4ozvchrcmutx6qfk.jpg",
        date: { dayStr: "Mon", dayNum: "11", month: "May", full: "Mon, 11 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-11T19:30:00+05:30",
        venue: "Himachal Pradesh Cricket Association Stadium, Dharamshala",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m11",
        matchNumber: "Match 56",
        team1: { name: "Gujarat Titans", short: "GT", cssClass: "gt", logo: TEAM_LOGOS["GT"] },
        team2: { name: "Sunrisers Hyderabad", short: "SRH", cssClass: "srh", logo: TEAM_LOGOS["SRH"] },
        heroBg: "",
        date: { dayStr: "Tue", dayNum: "12", month: "May", full: "Tue, 12 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-12T19:30:00+05:30",
        venue: "Narendra Modi Stadium, Ahmedabad",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m12",
        matchNumber: "Match 57",
        team1: { name: "Royal Challengers Bengaluru", short: "RCB", cssClass: "rcb", logo: TEAM_LOGOS["RCB"] },
        team2: { name: "Kolkata Knight Riders", short: "KKR", cssClass: "kkr", logo: TEAM_LOGOS["KKR"] },
        heroBg: "",
        date: { dayStr: "Wed", dayNum: "13", month: "May", full: "Wed, 13 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-13T19:30:00+05:30",
        venue: "Shaheed Veer Narayan Singh International Cricket Stadium, Raipur",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m13",
        matchNumber: "Match 58",
        team1: { name: "Punjab Kings", short: "PBKS", cssClass: "pbks", logo: TEAM_LOGOS["PBKS"] },
        team2: { name: "Mumbai Indians", short: "MI", cssClass: "mi", logo: TEAM_LOGOS["MI"] },
        heroBg: "",
        date: { dayStr: "Thu", dayNum: "14", month: "May", full: "Thu, 14 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-14T19:30:00+05:30",
        venue: "Himachal Pradesh Cricket Association Stadium, Dharamshala",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m14",
        matchNumber: "Match 59",
        team1: { name: "Lucknow Super Giants", short: "LSG", cssClass: "lsg", logo: TEAM_LOGOS["LSG"] },
        team2: { name: "Chennai Super Kings", short: "CSK", cssClass: "csk", logo: TEAM_LOGOS["CSK"] },
        heroBg: "",
        date: { dayStr: "Fri", dayNum: "15", month: "May", full: "Fri, 15 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-15T19:30:00+05:30",
        venue: "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m15",
        matchNumber: "Match 60",
        team1: { name: "Kolkata Knight Riders", short: "KKR", cssClass: "kkr", logo: TEAM_LOGOS["KKR"] },
        team2: { name: "Gujarat Titans", short: "GT", cssClass: "gt", logo: TEAM_LOGOS["GT"] },
        heroBg: "",
        date: { dayStr: "Sat", dayNum: "16", month: "May", full: "Sat, 16 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-16T19:30:00+05:30",
        venue: "Eden Gardens, Kolkata",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m16",
        matchNumber: "Match 61",
        team1: { name: "Punjab Kings", short: "PBKS", cssClass: "pbks", logo: TEAM_LOGOS["PBKS"] },
        team2: { name: "Royal Challengers Bengaluru", short: "RCB", cssClass: "rcb", logo: TEAM_LOGOS["RCB"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "17", month: "May", full: "Sun, 17 May 2026" },
        time: "3:30 PM",
        datetime: "2026-05-17T15:30:00+05:30",
        venue: "Himachal Pradesh Cricket Association Stadium, Dharamshala",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m17",
        matchNumber: "Match 62",
        team1: { name: "Delhi Capitals", short: "DC", cssClass: "dc", logo: TEAM_LOGOS["DC"] },
        team2: { name: "Rajasthan Royals", short: "RR", cssClass: "rr", logo: TEAM_LOGOS["RR"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "17", month: "May", full: "Sun, 17 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-17T19:30:00+05:30",
        venue: "Arun Jaitley Stadium, Delhi",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m18",
        matchNumber: "Match 63",
        team1: { name: "Chennai Super Kings", short: "CSK", cssClass: "csk", logo: TEAM_LOGOS["CSK"] },
        team2: { name: "Sunrisers Hyderabad", short: "SRH", cssClass: "srh", logo: TEAM_LOGOS["SRH"] },
        heroBg: "",
        date: { dayStr: "Mon", dayNum: "18", month: "May", full: "Mon, 18 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-18T19:30:00+05:30",
        venue: "MA Chidambaram Stadium, Chennai",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m19",
        matchNumber: "Match 64",
        team1: { name: "Rajasthan Royals", short: "RR", cssClass: "rr", logo: TEAM_LOGOS["RR"] },
        team2: { name: "Lucknow Super Giants", short: "LSG", cssClass: "lsg", logo: TEAM_LOGOS["LSG"] },
        heroBg: "",
        date: { dayStr: "Tue", dayNum: "19", month: "May", full: "Tue, 19 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-19T19:30:00+05:30",
        venue: "Sawai Mansingh Stadium, Jaipur",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m20",
        matchNumber: "Match 65",
        team1: { name: "Kolkata Knight Riders", short: "KKR", cssClass: "kkr", logo: TEAM_LOGOS["KKR"] },
        team2: { name: "Mumbai Indians", short: "MI", cssClass: "mi", logo: TEAM_LOGOS["MI"] },
        heroBg: "",
        date: { dayStr: "Wed", dayNum: "20", month: "May", full: "Wed, 20 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-20T19:30:00+05:30",
        venue: "Eden Gardens, Kolkata",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m21",
        matchNumber: "Match 66",
        team1: { name: "Gujarat Titans", short: "GT", cssClass: "gt", logo: TEAM_LOGOS["GT"] },
        team2: { name: "Chennai Super Kings", short: "CSK", cssClass: "csk", logo: TEAM_LOGOS["CSK"] },
        heroBg: "",
        date: { dayStr: "Thu", dayNum: "21", month: "May", full: "Thu, 21 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-21T19:30:00+05:30",
        venue: "Narendra Modi Stadium, Ahmedabad",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m22",
        matchNumber: "Match 67",
        team1: { name: "Sunrisers Hyderabad", short: "SRH", cssClass: "srh", logo: TEAM_LOGOS["SRH"] },
        team2: { name: "Royal Challengers Bengaluru", short: "RCB", cssClass: "rcb", logo: TEAM_LOGOS["RCB"] },
        heroBg: "",
        date: { dayStr: "Fri", dayNum: "22", month: "May", full: "Fri, 22 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-22T19:30:00+05:30",
        venue: "Rajiv Gandhi International Stadium, Hyderabad",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m23",
        matchNumber: "Match 68",
        team1: { name: "Lucknow Super Giants", short: "LSG", cssClass: "lsg", logo: TEAM_LOGOS["LSG"] },
        team2: { name: "Punjab Kings", short: "PBKS", cssClass: "pbks", logo: TEAM_LOGOS["PBKS"] },
        heroBg: "",
        date: { dayStr: "Sat", dayNum: "23", month: "May", full: "Sat, 23 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-23T19:30:00+05:30",
        venue: "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m24",
        matchNumber: "Match 69",
        team1: { name: "Mumbai Indians", short: "MI", cssClass: "mi", logo: TEAM_LOGOS["MI"] },
        team2: { name: "Rajasthan Royals", short: "RR", cssClass: "rr", logo: TEAM_LOGOS["RR"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "24", month: "May", full: "Sun, 24 May 2026" },
        time: "3:30 PM",
        datetime: "2026-05-24T15:30:00+05:30",
        venue: "Wankhede Stadium, Mumbai",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    },
    {
        id: "m25",
        matchNumber: "Match 70",
        team1: { name: "Kolkata Knight Riders", short: "KKR", cssClass: "kkr", logo: TEAM_LOGOS["KKR"] },
        team2: { name: "Delhi Capitals", short: "DC", cssClass: "dc", logo: TEAM_LOGOS["DC"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "24", month: "May", full: "Sun, 24 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-24T19:30:00+05:30",
        venue: "Eden Gardens, Kolkata",
        distance: "500 km away",
        basePrice: 2000,
        status: "live"
    }
    ,
    {
        id: "q1",
        matchNumber: "Qualifier 1",
        team1: { name: "TBD", short: "TBD", cssClass: "tbd", logo: TEAM_LOGOS["TBD"] },
        team2: { name: "TBD", short: "TBD", cssClass: "tbd", logo: TEAM_LOGOS["TBD"] },
        heroBg: "",
        date: { dayStr: "Tue", dayNum: "26", month: "May", full: "Tue, 26 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-26T19:30:00+05:30",
        venue: "Narendra Modi Stadium, Ahmedabad",
        distance: "600.0 km away",
        basePrice: 4000,
        status: "coming_soon"
    },
    {
        id: "final",
        matchNumber: "Final",
        team1: { name: "TBD", short: "TBD", cssClass: "tbd", logo: TEAM_LOGOS["TBD"] },
        team2: { name: "TBD", short: "TBD", cssClass: "tbd", logo: TEAM_LOGOS["TBD"] },
        heroBg: "",
        date: { dayStr: "Sun", dayNum: "31", month: "May", full: "Sun, 31 May 2026" },
        time: "7:30 PM",
        datetime: "2026-05-31T19:30:00+05:30",
        venue: "M. A. Chidambaram Stadium, Chennai",
        distance: "1400.0 km away",
        basePrice: 5000,
        status: "coming_soon"
    }
];

// Helper Functions
function getMatchById(id) {
    return matchesData.find(m => m.id === id);
}

function formatCurrency(amount) {
    return '₹' + Math.round(amount).toLocaleString('en-IN');
}
